title: Trịnh Quốc Cường - Portfolio
logo: /assets/img/image.jpg
description: "A portfolio showcasing my skills, projects, and experience in Software Engineering."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
